package nl.rug.oop.rts.controller;

import nl.rug.oop.rts.model.Edge;
import nl.rug.oop.rts.model.Graph;
import nl.rug.oop.rts.model.Node;

import javax.swing.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.Line2D;

/**
 * Class that handles mouse movement (pressed/released/clicked/moved).
 */
public class MouseGraphMoved extends MouseAdapter {
    private Graph graph;
    private JPanel panel;
    private Node node;
    private Edge edge;

    /**
     * Method that initialises the graph and panel.
     *
     * @param graph with nodes and edges
     * @param panel that is shown on screen
     */
    public MouseGraphMoved(Graph graph, JPanel panel) {
        this.graph = graph;
        this.panel = panel;
        this.node = null;
        this.edge = null;
    }

    @Override
    public void mousePressed(MouseEvent e) {
        super.mouseClicked(e);
        int check = 0;

        check = checkSelectNode(e);
        check = checkSelectEdge(e);

        graph.setAddingEdge(false);
        graph.notifyListeners();
        panel.requestFocusInWindow();
    }

    /**
     * Method that checks if a node is selected.
     *
     * @param e event generated by the mouse action
     * @return check which is 1 or 0
     */
    public int checkSelectNode(MouseEvent e) {
        int check = 0;
        for (Node node : graph.getNodes()) {
            if (clickedOnNode(node, e)) {
                if (graph.isAddingEdge()) {
                    if (graph.getFirstNode() != node) {
                        Edge test = new Edge("test", graph.getFirstNode(), node);
                        graph.addEdge(test);
                        break;
                    }
                }
                if (graph.getSelectedNode() == node) {
                    node.setSelected(false);
                    graph.setSelectedNode(null);
                    this.node = null;
                    check = 1;
                    break;
                } else {
                    if (graph.getSelectedNode() == null && graph.getSelectedEdge() == null) {
                        this.node = node;
                        graph.setSelectedNode(node);
                        node.setSelected(true);
                        check = 1;
                    }
                }
            }
        }
        return check;
    }

    /**
     * Method that checks if an edge is selected.
     *
     * @param e event generated by the mouse action
     * @return check which is 1 or 0
     */
    public int checkSelectEdge(MouseEvent e) {
        int check = 0;
        for (Edge edge : graph.getEdges()) {
            double lineStartX = edge.getStart().getX();
            double lineStartY = edge.getStart().getY();
            double lineEndX = edge.getEnd().getX();
            double lineEndY = edge.getEnd().getY();

            double distance = Line2D.ptSegDist(lineStartX, lineStartY, lineEndX, lineEndY, e.getX(), e.getY());

            if (distance < 5 && check == 0 && graph.getSelectedNode() == null) {
                if (this.edge == edge) {
                    this.edge = null;
                    graph.setSelectedEdge(null);
                    break;
                }
                this.edge = edge;
                graph.setSelectedEdge(edge);
            }
        }
        return check;
    }

    @Override
    public void mouseDragged(MouseEvent e) {
        super.mouseDragged(e);

        for (Node node : graph.getNodes()) {
            if (clickedOnNode(node, e) && graph.getSelectedNode() == node) {
                this.node = node;
                int halfWidth = 100 / 2;
                int halfHeight = 100 / 2;
                node.move(e.getX() - halfWidth, e.getY() - halfHeight, graph);
            }
        }
    }

    /**
     * Method that checks whether a node was clicked.
     *
     * @param node that was clicked
     * @param e    event generated by the mouse action
     * @return true or false, whether the node was clicked or not
     */
    public boolean clickedOnNode(Node node, MouseEvent e) {
        int x = node.getX();
        int endX = node.getX() + 100;
        int y = node.getY();
        int endY = node.getY() + 100;
        return (x <= e.getX()) && (endX >= e.getX()) && (y <= e.getY()) && (endY >= e.getY());
    }
}
